# Generated by Django 2.2.1 on 2019-05-10 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('timeOfConstruction', models.IntegerField(default=2000)),
                ('displayImage', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=30)),
                ('cardHolder', models.CharField(max_length=80)),
                ('expMonth', models.IntegerField()),
                ('expYear', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('aptSuite', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesCost', models.CharField(max_length=20)),
                ('appraisalCost', models.CharField(max_length=15)),
                ('photoCost', models.CharField(max_length=15)),
                ('managementCost', models.CharField(max_length=15)),
                ('dataCollection', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('desc', models.TextField()),
                ('registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('soldOnDate', models.DateTimeField(default=None)),
                ('openHouse', models.CharField(default=None, max_length=75)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartments')),
            ],
        ),
        migrations.CreateModel(
            name='listingDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(default=None, max_length=500)),
                ('description', models.CharField(default=None, max_length=500)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Listings')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Locations'),
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('aID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartments')),
            ],
        ),
    ]
